/*
 * Project name:
     TJ_GUI14e_v_1_1
 * Generated by:
     Visual TFT
 * Date of creation
     9/26/2017
 * Time of creation
     3:27:45 PM
 * Test configuration:
     MCU:             STM32F407VG
     Dev.Board:       Ploca_Igor
     Oscillator:      168000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
     Note:            Download FT812 library at
                      http://www.mikroe.com/visualtft/#FT812
                      Download (if using external memory storage) FAT32 library at
                      http://www.libstock.com/projects/view/108/fat32-library
 */

#include "TJ_GUI14e_v_1_1_objects.h"

void main() {

  InitVTFTStack();

  while (1) {
    ProcessVTFTStack();
  }

}
